import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import { FaGithub, FaTwitter, FaLinkedin } from 'react-icons/fa';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pedro Fontoura - Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          alt="Pedro Fontoura"
          height={200}
          width={200}
          src="/avatar.png"
          className={styles.avatar}
        />

        <h1 className={styles.title}>Hi, I&apos;m Pedro Fontoura.</h1>

        <p>
          I&apos;m a Computer Science student seeking professional experience to
          act in challenging environments, solving real-world problems using
          modern technologies.
        </p>

        <p>
          Currently working with <strong>TypeScript</strong>,{' '}
          <strong>Node.js</strong> and <strong>React</strong>.
        </p>

        <div className={styles.social}>
          <a href="https://github.com/pedr0fontoura">
            <FaGithub size={32} />
          </a>

          <a href="https://twitter.com/pedr0fontoura">
            <FaTwitter size={32} />
          </a>

          <a href="https://www.linkedin.com/in/pffrd/">
            <FaLinkedin size={32} />
          </a>
        </div>
      </main>
    </div>
  );
}
